chore: edit list when patch
ecomplus/admin pull request #270
Opened 2020-11-14 02:48 UTC by matheusgnreis

Before i only put edit visible in mass. But now, after patch i show to shoppers that products change to visible or not

2020-11-14 04:38 UTC, leomp12 requested changes

2020-11-14 04:38 UTC, leomp12 commented on src/controllers/resources/list/products.js
> +            if (typeof (bodyObject.available || bodyObject.visible) === 'boolean') {
Acho que isso aqui vai dar pau, não?
Teste setando a disponibilidade para `false` (indisponível), neste caso `(bodyObject.available || bodyObject.visible)` deve corresponder a `(false || undefined)` e o typeof será `'undefined'`, não vai entrar na condição e deveria porque a disponibilidade foi alterada...

2020-11-14 04:38 UTC, leomp12 commented on src/controllers/resources/list/products.js
> +            if (typeof (bodyObject.available || bodyObject.visible) === 'boolean') {
Acho que podia ser algo como:

```js
if (typeof bodyObject.available === 'boolean') {
 // o que já estava
} else if (typeof bodyObject.visible === 'boolean') {
  $items.each(function () {
    $(this).find('.item-visible')
      .html(`<i class="mr-2 fa fa-${(bodyObject.visible ? 'eye' : 'eye-slash')}"></i>`)
  })
}
```

2020-11-28 13:24 UTC, matheusgnreis commented on src/controllers/resources/list/products.js
> +            if (typeof (bodyObject.available || bodyObject.visible) === 'boolean') {
Fiz isso e dei um git rebase master para pegar as atualizações feitas

2020-12-07 16:44 UTC, leomp12 reviewed
@matheusgnreis rolou uma confusão com essa PR aqui pelo jeito :neutral_face: 
O que você alterou foi só `src/controllers/resources/list.js` ?

2020-12-07 21:08 UTC, matheusgnreis commented
Sim @leomp12, apliquei só um git rebase pra atualizar o repo que estava desatualizado

2020-12-07 21:12 UTC, leomp12 commented
Não usa `git rebase` assim isso não porque ele duplica os commits todos e avacalha a PR igual aqui, quando for assim melhor atualizar seu branch no GitHub mesmo e depois dá um pull.

2020-12-07 21:44 UTC, matheusgnreis commented
Se quiser, crio nova PR, já que é pouca coisa com repo já atualizado

2020-12-07 22:08 UTC, leomp12 commented
Aqui acho que precisa não, se você tem certeza que aqui tá mudando só o `src/controllers/resources/list.js` tá tranquilo..
Digo pras próximas mesmo...

2020-12-09 23:28 UTC, merged