fix: slug join without -
ecomplus/admin pull request #314
Opened 2021-01-28 18:49 UTC by matheusgnreis

2021-01-28 22:05 UTC, leomp12 commented on src/controllers/resources/form.js
> +                  console.log(clearAccents(data.name.toLowerCase(), '-'))
```suggestion
```

:neutral_face:

2021-01-28 22:05 UTC, leomp12 commented on src/script/util.js
> +      str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\s\n]/g, removeSpaces).replace(/[^a-z0-9_-]/ig, '')
Mockou o `-` e fez umas outras paradas aí que sei não em...
Tem certeza que isso funciona certinho em todos os acentos?

2021-01-28 22:08 UTC, leomp12 commented on src/script/util.js
> +      str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\s\n]/g, removeSpaces).replace(/[^a-z0-9_-]/ig, '')
O que eu tinha sugerido era só algo como:

```js
      str = str.replace(/[\s\n]/g, removeSpaces)
        .replace(new RegExp(`[^a-z0-9_${removeSpaces}]`, 'ig', '')
```

Acho que esse trecho aí funcionaria.

2021-01-28 22:09 UTC, leomp12 commented on src/script/util.js
> +      str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\s\n]/g, removeSpaces).replace(/[^a-z0-9_-]/ig, '')
O problema de mockar o `-` é que essa função não é usada só pra slug, é pra ser um utilitário, pode ser que em outro caso tenha que remover os hífens.

2021-01-28 22:23 UTC, matheusgnreis commented on src/script/util.js
> +      str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\s\n]/g, removeSpaces).replace(/[^a-z0-9_-]/ig, '')
eu testei pra ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐ ÑÒÓÔÕÖØÙÚÛÜ ÝŔÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿŕ e o slug foi aaaaaaceeeeiiii-nooooouuuu-yraaaaaaceeeeiiiinooooouuuuyyr, vou colocar:

[^a-z0-9_${removeSpaces}] também

2021-01-29 20:38 UTC, leomp12 requested changes

2021-01-29 20:38 UTC, leomp12 commented on src/script/util.js
> +      str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
Nesse caso esse trecho deveria estar fora do `if (removeSpaces) {` @matheusgnreis 
Com essa alteração aqui `clearAccents('atenção')` por exemplo ia retornar `'atenção'` e deveria retornar `'atencao`, quer dizer, a função deve remover os acentos (como fazia antes) mesmo se não for setado o `removeSpaces`.

2021-02-02 01:40 UTC, matheusgnreis commented on src/script/util.js
> +      str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
Ah sim, entendi

2021-02-03 00:16 UTC, leomp12 approved these changes
valeu @matheusgnreis

2021-02-03 00:16 UTC, leomp12 commented on src/controllers/invoices.js
> +    console.log(order)
:-1: 

```suggestion
```

2021-02-03 00:16 UTC, leomp12 commented on src/controllers/invoices.js
> +    console.log(order)
que mania de console log kkk

2021-02-03 00:16 UTC, leomp12 commented on src/script/util.js
> +    str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
agora sim :+1:

2021-02-03 00:17 UTC, merged