feat: add notes for products
ecomplus/admin pull request #378
Opened 2021-05-13 02:31 UTC by matheusgnreis

2021-05-19 21:08 UTC, leomp12 requested changes
Não deveria estar nesse card (_Organização_), talvez em um outro e fechado por padrão.

Não é a intenção simplesmente ir adicionando cada vez mais inputs nos formulários, principalmente em formulários que já estão "prontos" isso deve ser feito com cuidado e somente quando realmente for uma demanda relevante.

2021-05-19 22:20 UTC, matheusgnreis commented
Nota no produto, serve apenas para organização interna, por isso coloquei no campo. Já tinha essa demanda na e-com club, como solicitaram aqui também coloquei lá, mas vou inserir em um campo separado lá em baixo

2021-05-19 22:37 UTC, leomp12 commented
A _organização_ ali não é interna na verdade, é do catálogo, influencia em busca, separação na loja e etc...
Mas o principal motivo da separação é que categorias, marcas e palavras-chave são importantes e que se comunicam, notas é um campo bem secundário (a maioria dos lojistas não deve utilizar) e não tem sem relação com esses outros.

2021-05-21 22:14 UTC, matheusgnreis commented
Atualizei aqui

2021-05-21 23:31 UTC, leomp12 reviewed
Esse vai ser o menos importante e menos usado (pelo menos deveria já que os outros são mais funcionais) de todos os cards, deveria estar por último, não?

2021-05-21 23:31 UTC, leomp12 commented on src/views/resources/form/products.html
> +
```suggestion
```

2021-05-21 23:31 UTC, leomp12 commented on src/views/resources/form/products.html
> +                <span data-lang="en_us">Edit notes from product</span>
```suggestion
                <span data-lang="en_us">Edit product notes</span>
```

2021-05-21 23:31 UTC, leomp12 commented on src/views/resources/form/products.html
> +              </label>
```suggestion
```

Acho que esse label aí não agregou não...

2021-05-21 23:31 UTC, leomp12 commented on src/views/resources/form/products.html
> +              </label>
Acho até que pode confundir lembrando comentários de reviews ou coisa do tipo

2021-05-21 23:33 UTC, matheusgnreis commented on src/views/resources/form/products.html
> +
Eu não coloquei por último, porque tem gente que sabe que o último é o frete, ai não queria trazer essa estranheza, colocando entre os outros. Mas se achar que é melhor o último, coloco lá tbm

2021-05-21 23:35 UTC, matheusgnreis commented on src/views/resources/form/products.html
> +              </label>
Eu só joguei que era um padrão ter um label, mas acho que era melhor sem mesmo

2021-05-22 20:16 UTC, leomp12 commented on src/views/resources/form/products.html
> +                </small>
Só pra constar, as notas não terão aplicação no storefront mas o dado é público via API, não sei se você sabe disso mesmo e se essa frase aqui poderia levar o lojista a entender que é privado...

2021-05-22 20:20 UTC, matheusgnreis commented on src/views/resources/form/products.html
> +                </small>
Sim, pelo q já me foi falado que é local de observação de estoque normalmente. Tipo em qual prateleira fica

2021-05-22 20:31 UTC, leomp12 approved these changes

2021-05-22 20:32 UTC, merged