feat(form/orders) : insert subscriptions list
ecomplus/admin pull request #577
Opened 2022-08-08 21:28 UTC by matheusgnreis

2022-08-08 23:26 UTC, leomp12 commented on src/views/resources/form/orders.html
> +
```suggestion
```

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +
```suggestion
```

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +    }
Certo é usar i18n né..

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +                }
```suggestion
                <td><a href="/resources/orders/${order._id}">${order.number}</a></td>
                ${(order.status ? `<td>${parseStatus(order.status)}</td>` : '')}
```

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +                }
Parênteses no ternário concatenado aí..

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +      let url
```js
      let url
      const data = Data()
```

E aí você evita o `Data()` toda vez nas linhas abaixo...

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +        url = `orders.json?number=${order}`
```js
        url = `orders.json?_id=${data.subscription_order._id}&limit=1`
```

Sempre melhor filtrar por ID, ideal aqui seria listar os fields que você usa também:

```js
        url = `orders.json?_id=${data.subscription_order._id}&limit=1&fields=_id,...`
```

2022-08-08 23:26 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +            $listOfSubscriptions.append(renderSubs(order))
Uai mas na mesma tabela (da mesma forma) você renderiza tanto os períodos da assinatura (quando está no pedido original) quanto o pedido ogirinal da assinatura? Não tá ficando confuso isso?

2022-08-08 23:26 UTC, leomp12 commented on src/views/resources/form/orders.html
> +                <span data-lang="pt_br">Veja pedidos de assinatura</span>
Na verdade ele não _vê assinaturas_, é pra ver os períodos (ou faturas) da assinatura, não?
Ficou meio confuso pra mim...

2022-08-08 23:26 UTC, leomp12 commented on src/views/resources/form/orders.html
> +            </span>
Não é assinaturas 🤔 
Seriam faturas da assinatura ou coisa do tipo, não?

2022-08-08 23:26 UTC, leomp12 commented on src/views/resources/form/orders.html
> +            </span>
Quer dizer, quando você diz _assinaturas_ me leva a crer que vai mostrar cada assinatura que foi pra certo plano, não é isso aqui acontece aqui

2022-08-08 23:26 UTC, leomp12 commented on src/views/resources/form/orders.html
> +      <div class="card card-slided-up" id="subscriptions">
Eu acho que isso aqui deveria ser `display: none` por padrão, exibir só quando o pedido for uma assinatura ou período de uma assinatura, porque isso na verdade é a exceção, a maioria dos pedidos não é recorrente

2022-08-08 23:34 UTC, leomp12 commented on src/views/resources/form/orders.html
> +      <div class="card card-slided-up" id="subscriptions">
E porque também não é editável pelo painel

2022-08-09 01:05 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +            $listOfSubscriptions.append(renderSubs(order))
Como sugere? Mudar completamente o thead se for fatura ou se for a assinatura?

2022-08-09 14:45 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +            $listOfSubscriptions.append(renderSubs(order))
Na verdade acho que só tem que ser uma tabela se for uma assinatura, porque aí você pode listar vários pedidos (períodos) subsequentes do pedido original (a assinatura em si).
Se for um pedido derivado da assinatura você só vai linkar em algum lugar a assinatura original (sempre vai ser só uma, não é necessário lista ou tabela), tipo:

![Screenshot 2022-08-09 at 11-43-53 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/183678799-a92b598f-809d-489a-a2cd-e8431c8a9c99.png)

2022-08-09 15:50 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +    }
ok

2022-08-09 15:51 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +            $listOfSubscriptions.append(renderSubs(order))
beleuza

2022-08-10 17:10 UTC, leomp12 requested changes
😛

2022-08-10 17:10 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
Pq c tá mexendo nisso?

2022-08-10 17:10 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
Tem um comentário aí _BUG: sometimes $buyers and $buyerInfo was empty_, você tá desfazendo e aí se pá vai voltar a dar esse BO eventualmente 😬

2022-08-10 17:10 UTC, leomp12 commented on src/views/resources/form/orders.html
> +
```suggestion
```

2022-08-10 17:10 UTC, leomp12 commented on src/views/resources/form/orders.html
> +                <span data-lang="pt_br">Lista das faturas da assinatura</span>
```suggestion
                <span data-lang="en_us">List subscription invoices</span>
                <span data-lang="pt_br">Listar faturas da assinatura</span>
```

O link é um CTA...

2022-08-10 17:10 UTC, leomp12 commented on src/views/resources/form/orders.html
> +                        <span data-lang="pt_br">Criado</span>
```suggestion
                        <span data-lang="pt_br">Criado em</span>
```

2022-08-10 17:10 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +            <h4 class="mt-30"><a href="/resources/orders/${order._id}">${i18n(i19subscriptions)} #${order.number}</a></h4>
Mas aqui vai ficar _Assinatura**s** #1234567_? Meio ruim com o S (gramaticalmente incorreto) aí não ? 🙃

2022-08-10 17:10 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +            <h4 class="mt-30"><a href="/resources/orders/${order._id}">${i18n(i19subscriptions)} #${order.number}</a></h4>
A assinatura do pedido é sempre uma só (não existe assinaturaS do pedido), podem ser várias faturas da mesma assinatura...

2022-08-10 17:10 UTC, leomp12 commented on src/views/resources/form/orders.html
> +      <div class="card card-slided-up" id="subscription-invoices" style="display: none">
```suggestion
      <div class="card card-slided-up" data-id="subscription-invoices" style="display: none">
```

Se usar ID fixo vai dar bug abrindo mais de um pedido ao mesmo tempo no painel

2022-08-10 17:10 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +        document.getElementById('subscription-invoices').style.display = 'block'
ID fixo (quase) nunca, e bota um frufru tbm:

```suggestion
        $(`#${tabId}-subscription-invoices`).slideDown()
```

2022-08-10 17:11 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
Se a intenção foi só corrigir pro linter, muda `var` pra `let` e deixa o resto como estava...

2022-08-10 17:11 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
Aí você não alteraria o funcionamento

2022-08-10 17:52 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
Mudei, porque eu uso esse $buyers, pra inserir Assinatura #... abaixo do buyers. Da forma que ele foi declarado ali, ficou no escopo local e não conseguia usar fora. Só se eu declarasse de novo.

2022-08-11 00:20 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
Então, mas isso tava dentro do timeout por uma razão né 😬

2022-08-11 00:21 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
E pela mesma razão talvez você deva usar o `$buyer` onde você precisa dentro de um timeout também..

2022-08-11 00:21 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> -      $buyerInfo = $buyers.find('#t' + tabId + '-buyer-info')
E aí você usa `let` pra declarar essas variáveis aí

2022-08-11 01:32 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +            <h4 class="mt-30"><a href="/resources/orders/${order._id}">${i18n(i19subscriptions)} #${order.number}</a></h4>
Sim, vou criar um i19 pra esse singular ai

2022-08-11 19:34 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +        console.log(orderId)
```suggestion
```

2022-08-11 19:39 UTC, merged