chore(form/orders): insert description transaction on timeline status
ecomplus/admin pull request #578
Opened 2022-08-08 21:31 UTC by matheusgnreis

2022-08-08 23:41 UTC, leomp12 requested changes

2022-08-08 23:41 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +          })
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/map
> O método map não modifica o array original. No entanto, a função callback invocada por ele pode fazê-lo.

2022-08-08 23:41 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +          })
Esse trecho aí não tá mudando nada 🙃

2022-08-08 23:41 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +          })
Teria que ser um `forEach` ou `events = events.map`, mas na real já tem um `forEach` então é melhor você não percorrer mais uma vez o array desnecessariamente, adiciona isso dentro do loop que já existe..

2022-08-09 00:08 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +          })
> Esse trecho aí não tá mudando nada

No caso, eu apliquei errado, é isso? Porque o array está sendo modificado:
![image](https://user-images.githubusercontent.com/35343551/183535148-b3b0c1e0-3dea-4a9a-a244-47eab9eb298f.png)

2022-08-09 00:20 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +          })
Ah tá mudando porque você tá mudando o objeto por referência mesmo:

```js
event.payment_method = (getTransaction.payment_method && getTransaction.payment_method.name) || undefined
```

Mas eu acho que isso foi meio que na bamba 😄 
Seu `return event` não muda nada, poderia ser `return 'abacate'`, na verdade o `.map` não fez diferença aí, poderia ser `.forEach` ou outros métodos do prorotype do array, já que no fim das contas você tá mexendo no objeto de cada elemento por referência no callback.

2022-08-09 00:21 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +          })
De qualquer maneira, isso deveria estar no `.forEach` que já existe né

2022-08-09 00:25 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +            blockContent += `<p> ${i18n(eventObj.text)} ${eventObj.payment_method ? `<small>(${eventObj.payment_method})</small>` : ''} </p> `
```suggestion
            let paymentMethod
            if (data.transactions.length > 1 && event.type === 'payments_history') {
              const transaction = data.transactions.find(transaction => event.transaction_id === transaction._id)
              paymentMethod = transaction.payment_method && transaction.payment_method.name
            }
            blockContent += `<p> ${i18n(eventObj.text)} ${(paymentMethod ? `<small>(${paymentMethod})</small>` : '')} </p>`
```

2022-08-09 00:25 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +          })
```suggestion
```

2022-08-09 00:27 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +          })
Pronto

2022-08-09 00:30 UTC, matheusgnreis commented
Sim, vi aqui e usei errado mesmo, já estava ajustando antes de fazer ai

2022-08-09 00:33 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +              paymentMethod = (getTransaction.payment_method && getTransaction.payment_method.name) || undefined
O `getTransaction` (que vá lá deveria ser `transaction` porque `getTransaction` parece ser uma função) pode ser undefined aqui, se for esse trecho vai quebrar o código.
Em contrapartida se `getTransaction` não é undefined você sabe que `getTransaction.payment_method` existe (e portanto não precisa checá-lo) porque `payment_method` é required no objeto transaction (https://developers.e-com.plus/docs/api/#/store/orders/orders)

2022-08-09 00:33 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +              paymentMethod = (getTransaction.payment_method && getTransaction.payment_method.name) || undefined
E o ` || undefined` também é desnecessário aqui (não muda nada)

2022-08-09 00:33 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +              paymentMethod = (getTransaction.payment_method && getTransaction.payment_method.name) || undefined
```suggestion
              paymentMethod = getTransaction && getTransaction.payment_method.name
```

2022-08-09 00:34 UTC, leomp12 commented on src/controllers/resources/form/orders.js
> +              paymentMethod = (getTransaction.payment_method && getTransaction.payment_method.name) || undefined
> se for esse trecho vai quebrar o código

` can't get payment_method from undefined ...`

2022-08-09 00:56 UTC, matheusgnreis commented on src/controllers/resources/form/orders.js
> +              paymentMethod = (getTransaction.payment_method && getTransaction.payment_method.name) || undefined
Mudei nome agora também

2022-08-09 14:30 UTC, leomp12 approved these changes
valeu nog 👍🏾

2022-08-09 14:31 UTC, merged