chore(resource): insert choice checkbox to import with PUT instead of PATCH
ecomplus/admin pull request #670
Opened 2023-04-11 18:29 UTC by matheusgnreis

![image](https://user-images.githubusercontent.com/35343551/231254530-6aa4c9aa-6d1b-4040-b7bb-d97dd9decaf4.png)
Alguns lojistas sempre perguntam, como apagar determinada coisa via tabela, pelo PATCH, se não tem, não edita, isso acontece muito com variações. Mas em contrapartida, pessoal gosta muito também que dá pra editar só o que estiver na tabela, facilita muito nas edições por tabela. Por isso, pensei em incluir essa opção, por padrão não é, se clicar, ai vai sobrescrever. 
Mas isso também, as vezes pode atrapalhar, a pessoa clicar sem ler, acontece um pouco, coloquei de vermelho pra ver se a pessoa tente ver.

Se não for uma boa opção, ai talvez eu possa apenas colocar lá, se tiver variations e o lojista colocar uma prop false, eu coloco um variations: [] que removeria as variações. Veja o que acha e depois me fale.

2023-04-11 19:04 UTC, leomp12 requested changes
A feature é boa, mas tá meio jogadão 😬

2023-04-11 19:04 UTC, leomp12 commented on src/index.ejs
> +                <input type="checkbox" class="custom-control-input" id="method-put">
```suggestion
                <input type="checkbox" class="custom-control-input" data-id="method-put">
```

🙃

2023-04-12 02:17 UTC, matheusgnreis commented on src/index.ejs
> +                <input type="checkbox" class="custom-control-input" id="method-put">
Nessa seção ai, o index.js no caso, não cria o id através do data-id, porque já é o source do painel e não abas..

2023-04-12 02:18 UTC, matheusgnreis commented on src/index.ejs
> +                  <span style="color: var(--danger)" data-lang="pt_br">Sobrescrever <small style="color: var(--danger)">(Irá deletar propriedades que não estão na tabela e mudar as que estiverem)</sm
Aqui, seria o window.alert que você fala? Quando cara clicar lá..?

2023-04-13 15:45 UTC, leomp12 commented on src/index.ejs
> +                  <span style="color: var(--danger)" data-lang="pt_br">Sobrescrever <small style="color: var(--danger)">(Irá deletar propriedades que não estão na tabela e mudar as que estiverem)</sm
Não não haha

2023-04-13 15:45 UTC, leomp12 commented on src/index.ejs
> +                  <span style="color: var(--danger)" data-lang="pt_br">Sobrescrever <small style="color: var(--danger)">(Irá deletar propriedades que não estão na tabela e mudar as que estiverem)</sm
https://getbootstrap.com/docs/4.6/components/alerts/

2023-04-13 15:46 UTC, leomp12 commented on src/controllers/resources.js
> +          }))
Não era esse alert não 😄 
https://getbootstrap.com/docs/4.6/components/alerts/

2023-04-15 17:50 UTC, matheusgnreis commented
![image](https://user-images.githubusercontent.com/35343551/232245283-058e5b03-d925-433b-8139-6e83eee3d8db.png)

2023-04-15 22:30 UTC, leomp12 commented on src/index.ejs
> +              <div id="overwrite-alert" class="alert alert-danger i18n alert-dismissible fade show" role="alert">
```suggestion
              <div id="overwrite-alert" class="alert alert-warning mt-1 i18n alert-dismissible fade show" role="alert">
```

2023-04-15 22:30 UTC, leomp12 commented on src/index.ejs
> +                <span data-lang="pt_br">Se <b>sobrescrever</b> ativo, irá deletar propriedades que não estão na tabela e mudar as que estiverem</span>
```suggestion
                <span data-lang="en_us">If active will delete properties that are not in the table and change the ones that are</span>
                <span data-lang="pt_br">Se ativo irá deletar propriedades que não estão na tabela e mudar as que estiverem</span>
```

2023-04-15 22:31 UTC, leomp12 approved these changes
✌🏾

2023-04-15 22:31 UTC, merged