feat(abandoned-cart): abandoned cart list
ecomplus/admin pull request #680
Opened 2023-05-25 20:38 UTC by matheusgnreis

![image](https://github.com/ecomplus/admin/assets/35343551/cbf9383d-5fc6-4286-901e-8a602e83ecbb)

2023-05-28 01:32 UTC, leomp12 requested changes
Então, nós já conversamos sobre isso no Slack, do jeito que tá aqui não faz nem sentido...
Não dá pra começar a rota listando de uma vez todos os clientes da loja, depois você lista todos os carrinhos do período o tenta associar aos clientes que você armazenou em memória, isso vai vir com uma UX horrível e ainda corre o risco de você gerar bloqueios na API por rate limit enquanto roda essas agregações desnecessárias.

2023-05-28 01:40 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +              $in: [true]
Aqui nem deveria ter agregação, mas pra casos onde deve haver, `$in` é pra bater mais de um valor, não tem porque usar `$in` se você só compara um valor...
Só mencionando porque você usou isso em todos os filtros

2023-05-28 01:40 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +              $in: [true]
É só `login: true` mesmo

2023-05-28 01:45 UTC, leomp12 commented
Você só quer listar carrinhos abandonados  por período com dados do cliente?
Naturalmente a primeira request deveria ser listar os carrinhos, não tem porque usar agregação inclusive:
`GET /carts.json?created_at>=x&created_at<=y&completed=false&fields=created_at,customer,...`
Pega o resultado e agrupa (cria um objeto no código) por ID do cliente (entendi que quer fazer isso) mostrando somente o último (sort pelo `created_at`).
Você vai ter os IDs dos clientes, busca os dados com mais um GETs (de novo, não faz sentido usar agregação):
`GET /customers.json?_id=1,2,3...`
Mesmo que seja de 100 em 100, o correto de fato é paginar isso aí.

2023-06-12 23:30 UTC, matheusgnreis commented
Pronto, pegando ai 200 por vez via aggregate.

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +  }
```suggestion
  const cartUrl = domain && `https://${domain}/app/#/cart/`
```

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +            urlCart ? urlCart + cart.cartId : 'Sem url configurada',
```suggestion
            cartUrl ? cartUrl + cart.cartId : 'Sem URL configurada',
```

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +            urlCart ? urlCart + cart.cartId : 'Sem url configurada',
i18n nada né 😐

2023-06-13 21:51 UTC, leomp12 commented on src/script/main.js
> +           ) +
Não deveria ser um link aqui na real

2023-06-13 21:51 UTC, leomp12 commented on src/script/main.js
> +           ) +
Já tem um link pra carrinho dentro de pedidos, não tem porque esse relatório estar em um item da nav principal

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +            const loops = ids.length > 200 ? Math.ceil(ids.length / sizeArray) : 1
```suggestion
            const loops = ids.length > sizeArray ? Math.ceil(ids.length / sizeArray) : 1
```

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +              init++
Também conhecido como `index + 1`

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +              arraySliced = ids.slice(index * sizeArray, sizeArray * init)
```suggestion
              arraySliced = ids.slice(index * sizeArray, sizeArray * (index + 1))
```

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +
```suggestion
                        }
```

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +          }
Que `count`? 🤔

2023-06-13 21:51 UTC, leomp12 commented on src/controllers/abandoned-cart.js
> +                          $first: '$name'
Por que não o `display_name` aqui?
Mensagem de carrinho abandonado não deveria usar ele?

2023-06-15 13:41 UTC, matheusgnreis commented on src/controllers/abandoned-cart.js
> +              init++
Tenho que prestar atenção mais nas prs, fiz uma coisa usando init, depois não ia precisar mais e acabei deixando, esqueci de tirar.

2023-06-15 13:42 UTC, matheusgnreis commented on src/script/main.js
> +           ) +
Achei que ficaria estranho carrinho, mas mudo lá

2023-06-16 20:37 UTC, matheusgnreis commented
Pronto

2023-06-16 22:56 UTC, leomp12 commented on src/views/abandoned-cart.html
> +            </th>
```suggestion
            <th class="i18n">
              <span data-lang="en_us">Email</span>
              <span data-lang="pt_br">E-mail</span>
            </th>
```

2023-06-16 22:56 UTC, leomp12 approved these changes
👍🏾

2023-06-16 22:57 UTC, merged