chore(script-main): Update storage handling script in API v2
ecomplus/admin pull request #779
Opened 2024-02-29 20:54 UTC by wisley7l

2024-03-06 00:33 UTC, wisley7l commented
Setar uso do storage Bunny no ecomplus.app 

POST https://ecomplus.app/api/storage/buckets
**Headers**
```JSON
{
  "x-store-id": "$STOREID"
  "Authorization": "Bearer $ACCESS_TOKEN_STORE_API"
}
``` 

**body**
```JSON
{
  "storage":"bunny"
}
```

Caso contrario a tentativa será o uso do storage do GCP, isso considerando que há uma service account do GCP salva no Authetication do cloudCommerce da loja.

2024-03-06 22:20 UTC, leomp12 requested changes
@wisley7l na verdade o ideal aqui era não ter nenhuma alteração além do hostname e um thumbnail a mais pro `small`.
A variante `zoom` não é thumbnail e já existia nas versões anteriores.
A nova API deveria conseguir receber as requests anteriores "as is" e retornar a no mesmo padrão (assim como acontece com a versão nova da Store API), sem alterar por exemplo se tem extensão ou não nas keys...
Não esperava que fosse necessário essa `@v4` e todas essas condições a mais, o principal problema é ter que adaptar outros serviços que consomem storage API.

2024-03-06 22:20 UTC, leomp12 commented on src/script/main.js
> +                })
`baseKey` nesse caso sempre vai ter a extensão? Por que?

2024-03-06 22:20 UTC, leomp12 commented on src/script/main.js
> +                      newImg.src = baseUrl + thumbSizes[0].path + fileName
Se eu entendi na listagem nova as keys vão vir com a extensão, sempre .webp?

2024-03-06 22:23 UTC, leomp12 commented
> Se por acaso quiser testar o Adim como Bunny
> Setar uso do storage Bunny no ecomplus.app

Na verdade isso não é uma escolha, esse endpoint não deveria existir. Em serviço gerenciado (pago) o storage das imagens deve ser sempre no Bunny.

2024-03-06 22:28 UTC, leomp12 requested changes

2024-03-06 22:28 UTC, leomp12 commented on src/script/main.js
> +          size: isApiv2 ? 350 : 400,
Btw já é 350 na API tual, esse size é sobrescrito pelo que vem na resposta do upload

2024-03-06 22:28 UTC, leomp12 commented on src/script/main.js
> +                        const fallbackSrc = baseUrl + pathImg
Eu acho que isso aqui vai quebrar na API atual

2024-03-06 22:28 UTC, leomp12 commented on src/script/main.js
> +                        const fallbackSrc = baseUrl + pathImg
O `storeId` no `baseUrl` é de autenticação, o `storeId` no key faz parte da chave do objeto mesmo, sem qualquer um dos dois vai dar erro de autorização lá

2024-03-06 22:28 UTC, leomp12 commented on src/script/main.js
> +                        const fallbackSrc = baseUrl + pathImg
E pra compatibilidade retroativa deveria ser opcional, inclusive duplicado, na nova versão

2024-03-06 22:28 UTC, leomp12 commented on src/script/main.js
> +                        const fallbackSrc = baseUrl + pathImg
Até bom que explicita que o `storeId` tem que fazer parte da key do objeto (em storage compartilhado)

2024-03-07 16:22 UTC, wisley7l commented on src/script/main.js
> +                      newImg.src = baseUrl + thumbSizes[0].path + fileName
Na verdade é o antigo que sempre .webp, aqui é pq vinha com extensão já (avif, webp ou a extensão original da imagem sendo o ultimo caso para lojas que optarem por storage do GCP e com tier 0); 

Mas no proximo commit estou retirando isso, vou adquear conforme mencionou no inicio do Review ( com minimo de alterações possivéis)

2024-03-07 16:24 UTC, wisley7l commented on src/script/main.js
> +                })
"Achei" que seria mais fácil já vir com a extensão pq temos avif e webp.
Mas vou corrigir isso no proximo commit.

2024-03-07 16:26 UTC, wisley7l commented on src/script/main.js
> +              }
Lojas que optarem por storage do GCP e com tier 0, não realizariam as tranformações no CF com isso as imagens seriam as originais do upload, ou seja sem avif e/ou webp

2024-03-07 18:04 UTC, leomp12 reviewed
Acho que as alterações aqui sobre object key e formatos são mais pra posterior deleção, certo? O ideal seria que a Storage API recebesse a key (com ou sem extensão) e deletasse todas as variantes da imagem em uma request só, nesse caso você poderia até usar v4 pra identificar que só uma request de delete deve ser adicionada.

Como não tem um edge worker (acaba adicionando latência) na frente, vamos ter que usar <picture> no front para usar AVIF em browsers que suportam, por compatibilidade as imagens WebP devem ser usadas por padrão (salvas nos documentos de produtos, categorias, etc...), mas para indicar que a imagem .avif existe salve a imagem .webp com <filename>.avif.webp

2024-03-08 20:02 UTC, leomp12 commented on src/script/main.js
> +
```suggestion
```

2024-03-08 20:02 UTC, leomp12 commented on src/script/main.js
> +                picture.zoom = { url: baseUrl + baseKey.replace('.avif', '.webp') }
Ué, isso aqui não entendi

2024-03-08 20:02 UTC, leomp12 commented on src/script/main.js
> +                picture.zoom = { url: baseUrl + baseKey.replace('.avif', '.webp') }
.webp.webp ?

2024-03-08 20:59 UTC, leomp12 commented on src/script/main.js
>                  if (!/\.webp$/.test(baseKey)) {
```suggestion
                if (
                  (/^@v4/.test(baseKey) && !/\.thumbs\.[\w]+$/.test(baseKey))
                  || (!/\.webp$/.test(baseKey))
                ) {
```

2024-03-13 23:40 UTC, leomp12 commented on src/script/main.js
> +        : 's3/' + s3Method + '.json'
Vamos passar mas o ideal é que o backend novo suporte os mesmos ("as is") endpoints né

2024-03-13 23:40 UTC, leomp12 commented on src/script/main.js
> +        : 's3/' + s3Method + '.json'
Como conversamos...

2024-03-13 23:40 UTC, leomp12 commented on src/script/main.js
> +                  (/^@v4/.test(baseKey) && !/\.thumbs\.[\w]+$/.test(baseKey)) ||
```suggestion
                  (/^@v4/.test(baseKey) && /\.thumbs\.[\w]+$/.test(baseKey)) ||
```

2024-03-13 23:40 UTC, leomp12 commented on src/script/main.js
> +                  (/^@v4/.test(baseKey) && !/\.thumbs\.[\w]+$/.test(baseKey)) ||
`baseKey` (path + filename) da imagem de zoom **tem que ter** sufixo .thumbs. pra indicar que existem thumbnails (transformações) da imagem, certo?

2024-03-13 23:42 UTC, leomp12 commented on src/script/main.js
> +                  (/^@v4/.test(baseKey) && !/\.thumbs\.[\w]+$/.test(baseKey)) ||
> Vou supor que o backend já trata isso corretamente, salvando com `.thumbs.<ext>` a imagem de zoom que possui variantes criadas

2024-03-13 23:43 UTC, leomp12 approved these changes

2024-03-13 23:52 UTC, merged

2024-03-14 20:20 UTC, leomp12 commented on src/script/main.js
> +                  (/^@v4/.test(baseKey) && !/\.thumbs\.[\w]+$/.test(baseKey)) ||
Correto

2024-03-14 20:55 UTC, leomp12 commented on src/script/main.js
> +                  (/^@v4/.test(baseKey) && !/\.thumbs\.[\w]+$/.test(baseKey)) ||
https://github.com/ecomplus/admin/commit/dfaf4227e1e6b08219dfd3c17932efc589791507